_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '../yolov3/_base_/optimizer_270e.yml',
  '../yolov3/_base_/yolov3_darknet53.yml',
  '../yolov3/_base_/yolov3_reader.yml',
]

snapshot_epoch: 5
weights: https://paddledet.bj.bcebos.com/models/pedestrian_yolov3_darknet.pdparams

num_classes: 1

TrainDataset:
  !COCODataSet
    dataset_dir: dataset/pedestrian
    anno_path: annotations/instances_train2017.json
    image_dir: train2017
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    dataset_dir: dataset/pedestrian
    anno_path: annotations/instances_val2017.json
    image_dir: val2017

TestDataset:
  !ImageFolder
    anno_path: configs/pedestrian/pedestrian.json
