_BASE_: [
  '../datasets/coco_instance.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/mask_rtdetr_r50vd.yml',
  '_base_/mask_rtdetr_reader.yml',
]

weights: output/mask_rtdetr_r18_6x_coco/model_final
find_unused_parameters: True
log_iter: 5 # 200
save_dir: output/mask_rtdetr_r18_6x_coco

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet18_vd_pretrained.pdparams
ResNet:
  depth: 18
  variant: d
  return_idx: [0, 1, 2, 3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

MaskHybridEncoder:
  hidden_dim: 256
  use_encoder_idx: [3]
  num_encoder_layers: 1
  encoder_layer:
    name: TransformerLayer
    d_model: 256
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.
    activation: 'gelu'
  expansion: 0.5
  depth_mult: 1.0

MaskRTDETR:
  eval_idx: -1
  num_decoder_layers: 3
