_BASE_: [
  'mask_rcnn_r50_1x_coco.yml',
]
weights: output/mask_rcnn_r50_2x_coco/model_final

epoch: 24
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [16, 22]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500
