language: cpp
cache: ccache
sudo: required
dist: trusty
services:
  - docker
os:
  - linux
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
  ssh_known_hosts: 13.229.163.131
before_install:
  - sudo pip install -U virtualenv pre-commit pip
  - docker pull paddlepaddle/paddle:latest
  - git pull https://github.com/PaddlePaddle/PaddleDetection release/2.0-rc

script:
  - exit_code=0
  - .travis/precommit.sh || exit_code=$(( exit_code | $? ))
  # - docker run -i --rm -v "$PWD:/py_unittest" paddlepaddle/paddle:latest /bin/bash -c
  #   'cd /py_unittest; sh .travis/unittest.sh' || exit_code=$(( exit_code | $? ))
  - if [ $exit_code -eq 0  ]; then true; else exit 1; fi;

notifications:
  email:
    on_success: change
    on_failure: always
