architecture: DETR
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/vit_huge_mae_patch14_dec512d8b_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True

DETR:
  backbone: VisionTransformer
  neck: SimpleFeaturePyramid
  transformer: GroupDINOTransformer
  detr_head: DINOHead
  post_process: DETRBBoxPostProcess


VisionTransformer:
  patch_size: 16
  embed_dim: 1280
  depth: 32
  num_heads: 16
  mlp_ratio: 4
  qkv_bias: True
  drop_rate: 0.0
  drop_path_rate: 0.1
  lr_decay_rate: 0.7
  global_attn_indexes: [7, 15, 23, 31]
  use_abs_pos: False
  use_rel_pos: True
  rel_pos_zero_init: True
  window_size: 14
  out_indices: [ 31, ]

SimpleFeaturePyramid:
  out_channels: 256
  num_levels: 4

GroupDINOTransformer:
  num_queries: 900
  position_embed_type: sine
  pe_temperature: 20
  pe_offset: 0.0
  num_levels: 4
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  use_input_proj: False
  dropout: 0.0
  activation: relu
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  learnt_init_query: True
  dual_queries: True
  dual_groups: 10


DINOHead:
  loss:
    name: DINOLoss
    loss_coeff: {class: 1, bbox: 5, giou: 2}
    aux_loss: True
    matcher:
      name: HungarianMatcher
      matcher_coeff: {class: 2, bbox: 5, giou: 2}


DETRBBoxPostProcess:
  num_top_queries: 300
  dual_queries: True
  dual_groups: 10
