_BASE_: [
  '../datasets/dota.yml',
  '../runtime.yml',
  '_base_/s2anet_optimizer_2x.yml',
  '_base_/s2anet.yml',
  '_base_/s2anet_reader.yml',
]
weights: output/s2anet_conv_1x_dota/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams

ResNet:
  depth: 50
  variant: b
  norm_type: bn
  return_idx: [1,2,3]
  num_stages: 4

S2ANetHead:
  anchor_strides: [8, 16, 32, 64, 128]
  anchor_scales: [4]
  anchor_ratios: [1.0]
  anchor_assign: RBoxAssigner
  stacked_convs: 2
  feat_in: 256
  feat_out: 256
  num_classes: 15
  align_conv_type: 'Conv'  # AlignConv Conv
  align_conv_size: 3
  use_sigmoid_cls: True
  reg_loss_weight: [1.0, 1.0, 1.0, 1.0, 1.1]
  cls_loss_weight: [1.1, 1.05]
