architecture: YOLOv3
use_gpu: true
max_iters: 55000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
metric: COCO
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_obj365_pretrained.tar 
weights: output/yolov3_r50vd_dcn_obj365_pretrained_coco/model_final
num_classes: 80

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  ignore_thresh: 0.7
  label_smooth: true
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 40000
    - 50000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    with_background: False
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: False
    - !NormalizeBox {}
    - !CropImage
      batch_sampler: [[1, 1, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0],
        [1, 50, 0.3, 1.0, 0.5, 2.0, 0.1, 1.0],
        [1, 50, 0.3, 1.0, 0.5, 2.0, 0.3, 1.0],
        [1, 50, 0.3, 1.0, 0.5, 2.0, 0.5, 1.0],
        [1, 50, 0.3, 1.0, 0.5, 2.0, 0.7, 1.0],
        [1, 50, 0.3, 1.0, 0.5, 2.0, 0.9, 1.0],
        [1, 50, 0.3, 1.0, 0.5, 2.0, 0.0, 1.0]]
    - !RandomInterpImage
      target_size: 608
    - !RandomFlipImage
      is_normalized: True
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: False      
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
  - !Permute
    to_bgr: False
    channel_first: True
  batch_size: 8
  shuffle: true
  worker_num: 8
  bufsize: 32
  use_multi_process: true

EvalReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
    dataset_dir: dataset/coco
    anno_path: annotations/instances_val2017.json
    image_dir: val2017
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: False
    - !ResizeImage
      interp: 2 
      target_size: 608
    - !NormalizeImage
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      is_scale: False
      is_channel_first: False      
    - !Permute
      to_bgr: False
  batch_size: 8
  worker_num: 8
  bufsize: 32

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: annotations/instances_val2017.json
      with_background: False
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: False
    - !ResizeImage
      interp: 2 
      target_size: 608
    - !NormalizeImage
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      is_scale: False
      is_channel_first: False      
    - !Permute
      to_bgr: False
  batch_size: 1
