_BASE_: [
  'centernet_r50_140e_coco.yml'
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/LCNet_x1_0_pretrained.pdparams
weights: output/centernet_lcnet_1x_140e_coco/model_final

CenterNet:
  backbone: LCNet
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

LCNet:
  scale: 1.0
  feature_maps: [2, 3, 4, 5]

TrainReader:
  batch_size: 32