_BASE_: [
  'centernet_r50_140e_coco.yml'
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/GhostNet_x1_3_ssld_pretrained.pdparams
weights: output/centernet_ghostnet_1_3x_140e_coco/model_final

CenterNet:
  backbone: GhostNet
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

GhostNet:
  scale: 1.3
  conv_decay: 0.00004
  feature_maps: [4, 6, 12, 17]

TrainReader:
  batch_size: 32