_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '../cascade_rcnn/_base_/optimizer_1x.yml',
  '../cascade_rcnn/_base_/cascade_rcnn_r50_fpn.yml',
  '../cascade_rcnn/_base_/cascade_fpn_reader.yml',
]
weights: output/cascade_rcnn_r50_fpn_gn_2x_coco/model_final

FPN:
  out_channel: 256
  norm_type: gn

CascadeHead:
  head: CascadeXConvNormHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner

CascadeXConvNormHead:
  num_convs: 4
  mlp_dim: 1024
  norm_type: gn


epoch: 24
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [16, 22]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000
