metric: COCO
num_classes: 1

# Detection Dataset for training
TrainDataset:
  !COCODataSet
    image_dir: ''
    anno_path: annotations/train.json
    dataset_dir: dataset/mix_mot_ch
    # [mot_train, crowdhuman_train, crowdhuman_val]
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/val_half.json
    dataset_dir: dataset/MOT

TestDataset:
  !ImageFolder
    anno_path: annotations/val_half.json

# MOTDataset for MOT evaluation and inference
EvalMOTDataset0:
  !MOTImageFolder
    dataset_dir: dataset/mot
    data_root: MOT17/images/half
    keep_ori_im: True # set as True in DeepSORT and ByteTrack

TestMOTDataset0:
  !MOTImageFolder
    dataset_dir: dataset/mot
    keep_ori_im: True # set True if save visualization images or video


# MOTDataset for MOT evaluation and inference
EvalMOTDataset:
  !MOTImageFolder
    #dataset_dir: dataset/pipeline/hievemot
    #dataset_dir: dataset/pipeline/cvatmot
    #dataset_dir: dataset/pipeline/tianfumot # fall_zhu
    data_root: images
    #dataset_dir: dataset/mot
    #data_root: MOT17/images/half
    keep_ori_im: True # set as True in DeepSORT and ByteTrack

TestMOTDataset:
  !MOTImageFolder
    dataset_dir: dataset/mot
    keep_ori_im: True # set True if save visualization images or video
