_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/group_dino_r50.yml',
  '_base_/dino_reader.yml',
]

weights: output/group_dino_r50_4scale_1x_coco/model_final
find_unused_parameters: True
log_iter: 100