architecture: SSD
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_coco_pretrained.tar
load_static_weights: True

SSD:
  backbone: MobileNet
  ssd_head: SSDHead
  post_process: BBoxPostProcess

MobileNet:
  norm_decay: 0.
  scale: 1
  conv_learning_rate: 0.1
  extra_block_filters: [[256, 512], [128, 256], [128, 256], [64, 128]]
  with_extra_blocks: true
  feature_maps: [11, 13, 14, 15, 16, 17]

SSDHead:
  kernel_size: 1
  padding: 0
  anchor_generator:
    steps: [0, 0, 0, 0, 0, 0]
    aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
    min_ratio: 20
    max_ratio: 90
    base_size: 300
    min_sizes: [60.0, 105.0, 150.0, 195.0, 240.0, 285.0]
    max_sizes: [[], 150.0, 195.0, 240.0, 285.0, 300.0]
    offset: 0.5
    flip: true
    min_max_aspect_ratios_order: false

BBoxPostProcess:
  decode:
    name: SSDBox
  nms:
    name: MultiClassNMS
    keep_top_k: 200
    score_threshold: 0.01
    nms_threshold: 0.45
    nms_top_k: 400
    nms_eta: 1.0
