worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {prob: 0.5}
    - RandomExpand: {fill_value: [0., 0, 0.]}
    - RandomCrop: {prob: 0.8}
    - RandomFlip: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 1}
  batch_transforms:
    - BatchRandomResize: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  batch_size: 4
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: true
  transform_schedulers: # [start_epoch, stop_epoch)
    - RandomDistort: {start_epoch: 0, stop_epoch: 71}
    - RandomExpand: {start_epoch: 0, stop_epoch: 71}
    - RandomCrop: {start_epoch: 0, stop_epoch: 71}
    - BatchRandomResize: {start_epoch: 0, stop_epoch: 71}


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 4
  shuffle: false
  drop_last: false


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
