worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - DecodeOp: {}
    - ResizeOp: {target_size: [576, 320], keep_ratio: False, interp: 2}
    #- MixupOp: {alpha: 1.5, beta: 1.5}
    #- RandomDistortOp: {}
    #- RandomExpandOp: {fill_value: [123.675, 116.28, 103.53]}
    #- RandomCropOp: {}
    #- RandomFlipOp: {}
  batch_transforms:
    #- BatchRandomResizeOp: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBoxOp: {}
    - PadBoxOp: {num_max_boxes: 50}
    - BboxXYXY2XYWHOp: {}
    - NormalizeImageOp: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - PermuteOp: {}
    - Gt2YoloTargetOp:
        anchor_masks: [[8, 9, 10, 11], [4, 5, 6, 7], [0, 1, 2, 3]]
        anchors: [[6,16], [8,23], [11,32], [16,45],  [21,64], [30,90], [43,128], [60,180],  [85,255], [120,320], [170,320], [340,320]]
        downsample_ratios: [32, 16, 8]
        num_classes: 1
  batch_size: 1
  shuffle: false
  drop_last: true
  mixup_epoch: 250


EvalReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - DecodeOp: {}
    - ResizeOp: {target_size: [576, 320], keep_ratio: False, interp: 2}
    - NormalizeImageOp: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - PermuteOp: {}
  batch_size: 1
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 576, 320]
  sample_transforms:
    - DecodeOp: {}
    - ResizeOp: {target_size: [576, 320], keep_ratio: False, interp: 2}
    - NormalizeImageOp: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - PermuteOp: {}
  batch_size: 1
