_BASE_: [
  '../datasets/coco_instance.yml',
  '../runtime.yml',
  '../mask_rcnn/_base_/optimizer_1x.yml',
  '../mask_rcnn/_base_/mask_rcnn_r50_fpn.yml',
  '../mask_rcnn/_base_/mask_fpn_reader.yml',
]
weights: output/mask_rcnn_r50_fpn_gn_2x_coco/model_final

MaskRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: BBoxHead
  mask_head: MaskHead
  # post process
  bbox_post_process: BBoxPostProcess
  mask_post_process: MaskPostProcess

FPN:
  out_channel: 256
  norm_type: gn

BBoxHead:
  head: XConvNormHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner

XConvNormHead:
  num_convs: 4
  mlp_dim: 1024
  norm_type: gn

MaskHead:
  head: MaskFeat
  roi_extractor:
    resolution: 14
    sampling_ratio: 0
    aligned: True
  mask_assigner: MaskAssigner
  share_bbox_feat: False

MaskFeat:
  num_convs: 4
  out_channels: 256
  norm_type: gn


epoch: 24
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [16, 22]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000
