_BASE_: [
  '../datasets/coco_instance.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_inst_crn.yml',
  './_base_/ppyoloe_inst_reader.yml',
]

log_iter: 100
snapshot_epoch: 10
weights: output/ppyoloe_inst_crn_l_300e_coco/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams
depth_mult: 1.0
width_mult: 1.0
