architecture: RetinaNet
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams

RetinaNet:
  backbone: ResNet
  neck: FPN
  head: RetinaHead

ResNet:
  depth: 50
  variant: b
  norm_type: bn
  freeze_at: 0
  return_idx: [1,2,3]
  num_stages: 4

FPN:
  out_channel: 256
  spatial_scales: [0.125, 0.0625, 0.03125]
  extra_stage: 2
  has_extra_convs: true
  use_c5: false

RetinaHead:
  conv_feat:
    name: RetinaFeat
    feat_in: 256
    feat_out: 256
    num_convs: 4
    norm_type: null
    use_dcn: false
  anchor_generator:
    name: RetinaAnchorGenerator
    octave_base_scale: 4
    scales_per_octave: 3
    aspect_ratios: [0.5, 1.0, 2.0]
    strides: [8.0, 16.0, 32.0, 64.0, 128.0]
  bbox_assigner:
    name: MaxIoUAssigner
    positive_overlap: 0.5
    negative_overlap: 0.4
    allow_low_quality: true
  loss_class:
    name: FocalLoss
    gamma: 2.0
    alpha: 0.25
    loss_weight: 1.0
  loss_bbox:
    name: SmoothL1Loss
    beta: 0.0
    loss_weight: 1.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5
