_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetrv2_r50vd.yml',
  '_base_/rtdetrv2_reader.yml',
]

weights: output/rtdetrv2_r50vd_dsp_1x_coco/model_final
find_unused_parameters: True
log_iter: 200

pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/rtdetrv2_r50vd_6x_coco.pdparams

RTDETRTransformerv2:
  cross_attn_sampling_method: discrete


epoch: 12

OptimizerBuilder:
  optimizer:
    type: AdamW
    weight_decay: 0.0001
    param_groups:
      - params: ['^(?=.*backbone)(?!.*norm).*$']
        learning_rate: 0.00001
      - params: ['^(?=.*(?:neck|transformer))(?=.*(?:norm|bn)).*$']
        weight_decay: 0.


TrainReader:
  transform_schedulers:
    - RandomDistort: {start_epoch: 0, stop_epoch: 10}
    - RandomExpand: {start_epoch: 0, stop_epoch: 10}
    - RandomCrop: {start_epoch: 0, stop_epoch: 10}
    - BatchRandomResize: {start_epoch: 0, stop_epoch: 10}