# This config is an assembled config for ByteTrack MOT, used as eval/infer mode for MOT.
_BASE_: [
  '../../runtime.yml',
  '../../yolov3/yolov3_darknet53_270e_coco.yml',
  '_base_/mix_mot17_ch.yml',
  '_base_/optimizer_80e.yml',
  '_base_/yolov3_mot_reader_608x608.yml'
]
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/yolov3_darknet53_270e_coco.pdparams
snapshot_epoch: 5

# metric: COCO # detection train/eval/infer/export mode
metric: MCMOT # MOT eval/infer mode
num_classes: 1

architecture: ByteTrack
ByteTrack:
  detector: YOLOv3 # General YOLOv3 version
  reid: None
  tracker: JDETracker
weights: output/bytetrack_yolov3_darknet53_80e/model_final
reid_weights: None

YOLOv3:
  backbone: DarkNet
  neck: YOLOv3FPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

TrainReader:
  batch_size: 8
  mixup_epoch: 70

EvalMOTReader:
  batch_size: 1 # Note batch_size should be 1 in MOT

# Tracking requires higher quality boxes, so decode.conf_thresh will be higher
BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.1 # 0.005 in original detector
    downsample_ratio: 32
    clip_bbox: true
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.1
    nms_threshold: 0.45
    nms_top_k: 1000

# BYTETracker
JDETracker:
  use_byte: True
  match_thres: 0.9
  conf_thres: 0.2
  low_conf_thres: 0.1
  min_box_area: 0
  vertical_ratio: 1.6 # for pedestrian
