# config of tracker for MOT SDE Detector, use 'OCSORTTracker' as default, 'JDETracker' here is just BYTETracker.
# The tracker of MOT JDE Detector (such as FairMOT) is exported together with the model.
# Here 'min_box_area' and 'vertical_ratio' are set for pedestrian, you can modify for other objects tracking.

type: BOTSORTTracker # choose one tracker in ['JDETracker', 'OCSORTTracker', 'DeepSORTTracker','BOTSORTTracker']
# When using for MTMCT(Multi-Target Multi-Camera Tracking), you should modify to 'DeepSORTTracker'


# just as BYTETracker, used for FairMOT in PP-Tracking project and for ByteTrack in PP-Humanv1 project
JDETracker:
  use_byte: True
  det_thresh: 0.3
  conf_thres: 0.6
  low_conf_thres: 0.1
  match_thres: 0.9
  min_box_area: 0
  vertical_ratio: 0 # 1.6 for pedestrian


# used for OC-SORT in PP-Humanv2 project and PP-Vehicle project
OCSORTTracker:
  det_thresh: 0.4
  max_age: 30
  min_hits: 3
  iou_threshold: 0.3
  delta_t: 3
  inertia: 0.2
  min_box_area: 0
  vertical_ratio: 0
  use_byte: False
  use_angle_cost: False


# used for DeepSORT and MTMCT in PP-Tracking project
DeepSORTTracker:
  input_size: [64, 192] # An unique operation to scale the sub-image of the selected detected boxes to a fixed size
  min_box_area: 0
  vertical_ratio: -1
  budget: 100
  max_age: 70
  n_init: 3
  metric_type: cosine
  matching_threshold: 0.2
  max_iou_distance: 0.9

BOTSORTTracker:
  track_high_thresh: 0.3
  track_low_thresh: 0.2
  new_track_thresh: 0.4
  match_thresh: 0.7
  track_buffer: 30
  min_box_area: 0
  camera_motion: False
  cmc_method: 'sparseOptFlow' # only camera_motion is True,
                              # sparseOptFlow | files (Vidstab GMC) | orb | ecc
