architecture: FasterRCNN
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
load_static_weights: True

# Model Achitecture
FasterRCNN:
  # model anchor info flow
  anchor: Anchor
  proposal: Proposal
  # model feat info flow
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: BBoxHead
  # post process
  bbox_post_process: BBoxPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4
  variant: d
  dcn_v2_stages: [1, 2, 3]
  lr_mult: [0.05, 0.05, 0.1, 0.15]

FPN:
  in_channels: [256, 512, 1024, 2048]
  out_channel: 64
  min_level: 0
  max_level: 4
  spatial_scale: [0.25, 0.125, 0.0625, 0.03125]

RPNHead:
  rpn_feat:
    name: RPNFeat
    feat_in: 64
    feat_out: 64
  anchor_per_position: 3
  rpn_channel: 64

Anchor:
  anchor_generator:
    name: AnchorGeneratorRPN
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_start_size: 32
    stride: [4., 4.]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_target_generator:
    name: AnchorTargetGeneratorRPN
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    straddle_thresh: 0.0
    use_random: True

Proposal:
  proposal_generator:
    name: ProposalGenerator
    min_size: 0.0
    nms_thresh: 0.7
    train_pre_nms_top_n: 2000
    train_post_nms_top_n: 2000
    infer_pre_nms_top_n: 500
    infer_post_nms_top_n: 300
  proposal_target_generator:
    name: LibraProposalTargetGenerator
    batch_size_per_im: 512
    bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
    bg_thresh_hi: [0.5,]
    bg_thresh_lo: [0.0,]
    fg_thresh: [0.5,]
    fg_fraction: 0.25
    use_random: True

BBoxHead:
  bbox_feat:
    name: BBoxFeat
    roi_extractor:
      name: RoIAlign
      resolution: 7
      sampling_ratio: 2
      canconical_level: 4
      canonical_size: 224
      end_level: 3
      start_level: 0
    head_feat:
      name: TwoFCHead
      in_dim: 64
      mlp_dim: 1024
  in_feat: 1024
  bbox_loss: DiouLoss

DiouLoss:
  loss_weight: 10.0
  is_cls_agnostic: false
  use_complete_iou_loss: true

BBoxPostProcess:
  decode:
    name: RCNNBox
    num_classes: 81
    batch_size: 1
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5
