_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/retinanet_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/retinanet_reader.yml'
]

worker_num: 4
TrainReader:
  batch_size: 4
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: true, interp: 1}
  - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  - Permute: {}

weights: output/retinanet_r50_fpn_mstrain_1x_coco/model_final
find_unused_parameters: true
