worker_num: 2
TrainReader:
  sample_transforms:
    - Decode: {}
    - Cutmix: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {aspect_ratio: NULL, cover_all_box: True}
    - RandomFlip: {}
    - GridMask: {upper_iter: 300000}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512], random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375], is_scale: false}
    - Permute: {}
    - Gt2TTFTarget: {down_ratio: 4}
    - PadBatch: {pad_to_stride: 32}
  batch_size: 12
  shuffle: true
  drop_last: true
  use_shared_memory: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 1, target_size: [320, 320], keep_ratio: False}
  - NormalizeImage: {is_scale: false, mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375]}
  - Permute: {}
  batch_size: 1
  drop_last: false
  drop_empty: false

TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 1, target_size: [320, 320], keep_ratio: False}
  - NormalizeImage: {is_scale: false, mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375]}
  - Permute: {}
  batch_size: 1
  drop_last: false
  drop_empty: false
