architecture: RetinaNet
max_iters: 90000
use_gpu: true
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet101_pretrained.tar
weights: output/retinanet_r101_fpn_1x/model_final
log_iter: 20
snapshot_iter: 10000
metric: COCO
save_dir: output
num_classes: 81

RetinaNet:
  backbone: ResNet
  fpn: FPN
  retina_head: RetinaHead

ResNet:
  norm_type: affine_channel
  norm_decay: 0.
  depth: 101
  feature_maps: [3, 4, 5]
  freeze_at: 2

FPN:
  max_level: 7
  min_level: 3
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125]
  has_extra_convs: true

RetinaHead:
  num_convs_per_octave: 4
  num_chan: 256
  max_level: 7
  min_level: 3
  prior_prob: 0.01
  base_scale: 4
  num_scales_per_octave: 3
  anchor_generator:
    aspect_ratios: [1.0, 2.0, 0.5]
    variance: [1.0, 1.0, 1.0, 1.0]
  target_assign:
    positive_overlap: 0.5
    negative_overlap: 0.4
  gamma: 2.0
  alpha: 0.25
  sigma: 3.0151134457776365
  output_decoder:
    score_thresh: 0.05
    nms_thresh: 0.5
    pre_nms_top_n: 1000
    detections_per_im: 100
    nms_eta: 1.0

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [60000, 80000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'faster_fpn_reader.yml'
TrainReader:
  batch_size: 2
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128

EvalReader:
  batch_size: 2
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128

TestReader:
  batch_size: 1
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
