architecture: CascadeRCNN
use_gpu: true
log_iter: 50
save_dir: output
snapshot_iter: 10000
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/dygraph/resnet50.pdparams
weights: output/cascade_rcnn_r50_1x/model_final
num_classes: 81
num_stages: 3
open_debug: False

# Model Achitecture
CascadeRCNN:
  # model anchor info flow
  anchor: AnchorRPN
  proposal: Proposal
  mask: Mask
  # model feat info flow
  backbone: ResNet
  rpn_head: RPNHead
  bbox_head: BBoxHead
  mask_head: MaskHead

ResNet:
  norm_type: 'affine'
  depth: 50
  freeze_at: 'res2'

RPNHead:
  rpn_feat:
    name: RPNFeat
    feat_in: 1024
    feat_out: 1024
  anchor_per_position: 15

BBoxHead:
  bbox_feat:
    name: BBoxFeat
    feat_in: 1024
    feat_out: 512
    roi_extractor:
      resolution: 14
      sampling_ratio: 0
      spatial_scale: 0.0625
      extractor_type: 'RoIAlign'

MaskHead:
  mask_feat:
    name: MaskFeat
    feat_in: 2048
    feat_out: 256
  feat_in: 256
  resolution: 14

AnchorRPN:
  anchor_generator:
    name: AnchorGeneratorRPN
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_target_generator:
    name: AnchorTargetGeneratorRPN
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    straddle_thresh: 0.0

Proposal:
  proposal_generator:
    name: ProposalGenerator
    min_size: 0.0
    nms_thresh: 0.7
    train_pre_nms_top_n: 2000
    train_post_nms_top_n: 2000
    infer_pre_nms_top_n: 2000
    infer_post_nms_top_n: 2000
    return_rois_num: True
  proposal_target_generator:
    name: ProposalTargetGenerator
    batch_size_per_im: 512
    bbox_reg_weights: [[0.1, 0.1, 0.2, 0.2],[0.05, 0.05, 0.1, 0.1],[0.333333, 0.333333, 0.666666, 0.666666]]
    bg_thresh_hi: [0.5, 0.6, 0.7]
    bg_thresh_lo: [0.0, 0.0, 0.0]
    fg_thresh: [0.5, 0.6, 0.7]
    fg_fraction: 0.25
  bbox_post_process: # used in infer
    name: BBoxPostProcess
    # decode -> clip -> nms
    decode_clip_nms:
      name: DecodeClipNms
      keep_top_k: 100
      score_threshold: 0.05
      nms_threshold: 0.5

Mask:
  mask_target_generator:
    name: MaskTargetGenerator
    resolution: 14
  mask_post_process:
    name: MaskPostProcess
