worker_num: 2
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  sample_transforms:
  - DecodeImage: {to_rgb: true}
  # check
  # - RandomFlipImage: {prob: 0.5}
  - NormalizeImage: {is_channel_first: false, is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeImage: {target_size: 800, max_size: 1333, interp: 1, use_cv2: true}
  - Permute: {to_bgr: false, channel_first: true}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1, use_padded_im_info: false, pad_gt: true}
  batch_size: 1
  shuffle: false
  drop_last: true


EvalReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
  sample_transforms:
  - DecodeOp: { }
  - NormalizeImageOp: { is_scale: true, mean: [ 0.485,0.456,0.406 ], std: [ 0.229, 0.224,0.225 ] }
  - ResizeOp: { interp: 1, target_size: [ 800, 1333 ] }
  - PermuteOp: { }
  batch_transforms:
  - PadBatchOp: { pad_to_stride: -1, pad_gt: false }
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false


TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id']
  sample_transforms:
  - DecodeImage: {to_rgb: true, with_mixup: false}
  - NormalizeImage: {is_channel_first: false, is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeImage: {interp: 1, max_size: 1333, target_size: 800, use_cv2: true}
  - Permute: {channel_first: true, to_bgr: false}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1, use_padded_im_info: false, pad_gt: false}  
  batch_size: 1
  shuffle: false
  drop_last: false
