worker_num: 2
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  sample_transforms:
    - DecodeOp: {}
    - MixupOp: {alpha: 1.5, beta: 1.5}
    - RandomDistortOp: {}
    - RandomExpandOp: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCropOp: {}
    - RandomFlipOp: {}
  batch_transforms:
  - BatchRandomResizeOp: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608], random_size: True, random_inter: True}
  - NormalizeImageOp: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
  - PermuteOp: {}
  - NormalizeBoxOp: {}
  - PadBoxOp: {num_max_boxes: 50}
  - BboxXYXY2XYWHOp: {}
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - Gt2YoloTargetOp: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 8
  shuffle: true
  drop_last: true


EvalReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
    num_max_boxes: 50
  sample_transforms:
    - DecodeOp: {}
    - ResizeOp: {target_size: 608, keep_ratio: False, interp: 2}
    - NormalizeImageOp: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - PadBoxOp: {num_max_boxes: 50}
    - PermuteOp: {}
  batch_size: 1
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  sample_transforms:
    - DecodeOp: {}
    - ResizeOp: {target_size: 608, interp: 2}
    - NormalizeImageOp: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - PermuteOp: {}
  batch_size: 1
