_BASE_: [
  '../../datasets/dota_ms.yml',
  '../../runtime.yml',
  '_base_/optimizer_3x.yml',
  '_base_/ppyoloe_r_reader.yml',
  '_base_/ppyoloe_r_crn.yml'
]

log_iter: 50
snapshot_epoch: 1
weights: output/ppyoloe_r_crn_l_3x_dota/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams
depth_mult: 1.0
width_mult: 1.0
