_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/sparse_rcnn_r50_fpn.yml',
  '_base_/optimizer_3x.yml',
  '_base_/sparse_rcnn_reader.yml',
]

num_classes: 80
weights: output/sparse_rcnn_r50b_fpn_pro300/model_final

snapshot_epoch: 1


SparseRCNNHead:
  num_proposals: 300

SparsePostProcess:
  num_proposals: 300
